export type SessionEngineRouteContract = {
  path: string;
  method: 'GET' | 'POST';
  engineMethod: string;
  requiredFields?: string[];
  responseKeys: string[];
  failureStatuses: number[];
  behavior: string;
};

export const SESSION_ENGINE_ROUTE_CONTRACTS: SessionEngineRouteContract[] = [
  {
    path: '/chat/send',
    method: 'POST',
    engineMethod: 'sendDesktopMessage',
    responseKeys: ['success', 'queued', 'queueId', 'isInFlight', 'deliveryMode'],
    failureStatuses: [400, 429, 500],
    behavior: 'Desktop admission returns before external runtime dispatch completes.',
  },
  {
    path: '/chat/stop',
    method: 'POST',
    engineMethod: 'stopTurn',
    responseKeys: ['success', 'alreadyStopped'],
    failureStatuses: [500],
    behavior: 'Stops active external process or builtin turn; external-inactive keeps builtin fallback.',
  },
  {
    path: '/chat/queue/cancel',
    method: 'POST',
    engineMethod: 'cancelQueuedMessage',
    requiredFields: ['queueId'],
    responseKeys: ['success', 'cancelledText', 'error'],
    failureStatuses: [400, 404, 409, 500, 503],
    behavior: 'Cancels queued messages in the active engine without touching completed turns.',
  },
  {
    path: '/chat/queue/force',
    method: 'POST',
    engineMethod: 'forceQueuedMessage',
    requiredFields: ['queueId'],
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 404, 500],
    behavior: 'Interrupts current turn and promotes the queued item for the active engine.',
  },
  {
    path: '/chat/queue/status',
    method: 'GET',
    engineMethod: 'getQueueStatus',
    responseKeys: ['success', 'queue'],
    failureStatuses: [],
    behavior: 'Reports the active engine queue snapshot.',
  },
  {
    path: '/cron/execute',
    method: 'POST',
    engineMethod: 'enqueueBackgroundMessage',
    requiredFields: ['taskId', 'prompt'],
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 500, 503],
    behavior: 'Accepts an async cron turn without waiting for assistant completion.',
  },
  {
    path: '/cron/execute-sync',
    method: 'POST',
    engineMethod: 'runInjectedTurn',
    requiredFields: ['taskId', 'prompt'],
    responseKeys: ['success', 'aiRequestedExit', 'exitReason', 'outputText', 'sessionId', 'error'],
    failureStatuses: [400, 408, 500, 503],
    behavior: 'Runs a synchronous cron turn and gates completion on the active engine success signal.',
  },
  {
    path: '/api/im/enqueue',
    method: 'POST',
    engineMethod: 'enqueueImMessage',
    requiredFields: ['requestId'],
    responseKeys: ['success', 'requestId', 'accepted', 'sessionId', 'error'],
    failureStatuses: [400, 500, 503],
    behavior: 'Accepts an IM message synchronously without waiting for the assistant turn.',
  },
  {
    path: '/api/im/cancel',
    method: 'POST',
    engineMethod: 'cancelImRequest',
    requiredFields: ['requestId'],
    responseKeys: ['success', 'requestId', 'mode', 'error'],
    failureStatuses: [400, 404, 409, 500],
    behavior: 'Cancels an IM request by requestId while keeping registry and bus cleanup in the route.',
  },
  {
    path: '/api/im/heartbeat',
    method: 'POST',
    engineMethod: 'runInjectedTurn',
    requiredFields: ['prompt', 'source', 'sourceId'],
    responseKeys: ['status', 'text', 'reason'],
    failureStatuses: [500],
    behavior: 'Runs a synchronous heartbeat turn and lets the route own event drain/requeue semantics.',
  },
  {
    path: '/api/memory/update',
    method: 'POST',
    engineMethod: 'runInjectedTurn',
    requiredFields: ['source'],
    responseKeys: ['status', 'reason'],
    failureStatuses: [500],
    behavior: 'Injects memory maintenance through the active engine and gates completion on true turn success.',
  },
  {
    path: '/api/inbox/drain',
    method: 'POST',
    engineMethod: 'enqueueInboxMessage',
    requiredFields: ['messages'],
    responseKeys: ['accepted', 'reason'],
    failureStatuses: [400, 409, 500],
    behavior: 'Audited injection path for sidecar-to-sidecar session events; does not wait for turn completion.',
  },
  {
    path: '/api/model/set',
    method: 'POST',
    engineMethod: 'updateModel',
    requiredFields: ['model'],
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 500],
    behavior: 'Updates active engine model; builtin preserves imConfigSync snapshot guard.',
  },
  {
    path: '/api/reasoning-effort/set',
    method: 'POST',
    engineMethod: 'updateReasoningEffort',
    requiredFields: ['effort'],
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 500],
    behavior: 'Updates active engine reasoning effort.',
  },
  {
    path: '/api/session/permission-mode',
    method: 'POST',
    engineMethod: 'updatePermissionMode',
    requiredFields: ['permissionMode'],
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 500],
    behavior: 'Updates active engine permission mode.',
  },
  {
    path: '/api/runtime/config',
    method: 'POST',
    engineMethod: 'updateRuntimeConfig',
    responseKeys: ['success', 'error', 'skipped'],
    failureStatuses: [400, 500],
    behavior: 'Applies external runtime config only; builtin returns a 400-compatible error.',
  },
  {
    path: '/api/runtime/prewarm',
    method: 'POST',
    engineMethod: 'prewarm',
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 500],
    behavior: 'Pre-warms external runtimes only.',
  },
  {
    path: '/api/runtime/permission-response',
    method: 'POST',
    engineMethod: 'respondExternalPermission',
    requiredFields: ['requestId'],
    responseKeys: ['success', 'error'],
    failureStatuses: [400, 500],
    behavior: 'Responds to external runtime permission requests directly, preserving legacy no-op success when no external process is active.',
  },
  {
    path: '/api/permission/respond',
    method: 'POST',
    engineMethod: 'respondPermission',
    requiredFields: ['requestId'],
    responseKeys: ['success', 'error'],
    failureStatuses: [500],
    behavior: 'Responds to builtin/external permission requests through the active engine.',
  },
  {
    path: '/api/im/permission-response',
    method: 'POST',
    engineMethod: 'respondPermission',
    requiredFields: ['requestId'],
    responseKeys: ['success', 'error'],
    failureStatuses: [500],
    behavior: 'Responds to IM approval-card permission requests through the active engine.',
  },
  {
    path: '/api/ask-user-question/respond',
    method: 'POST',
    engineMethod: 'respondAskUserQuestion',
    requiredFields: ['requestId'],
    responseKeys: ['success', 'error'],
    failureStatuses: [500],
    behavior: 'Routes ask-user-question responses by pending request ownership.',
  },
];

export function findSessionEngineRouteContract(
  path: string,
  method: string,
): SessionEngineRouteContract | undefined {
  return SESSION_ENGINE_ROUTE_CONTRACTS.find(
    (contract) => contract.path === path && contract.method === method,
  );
}
